# Generated by Django 3.0.4 on 2020-04-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lich', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boiler',
            name='id',
        ),
        migrations.RemoveField(
            model_name='diln',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kms',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kotel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lich',
            name='id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.RemoveField(
            model_name='typel',
            name='id',
        ),
        migrations.AlterField(
            model_name='boiler',
            name='blr_kod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='diln',
            name='diln_kod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='diln',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='kms',
            name='kms_kod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='kms',
            name='kms_name_full',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ремарка'),
        ),
        migrations.AlterField(
            model_name='kotel',
            name='kot_kod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_kod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='typel',
            name='diam',
            field=models.IntegerField(blank=True, verbose_name='Діаметр'),
        ),
        migrations.AlterField(
            model_name='typel',
            name='type_kod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='lich',
            name='boiler',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='lich.Boiler', verbose_name='Бойлерна'),
        ),
        migrations.AlterField(
            model_name='lich',
            name='diln',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Diln', verbose_name='Дільниця'),
        ),
        migrations.AlterField(
            model_name='lich',
            name='kms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Kms', verbose_name='Місце встан'),
        ),
        migrations.AlterField(
            model_name='lich',
            name='kod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код ліч'),
        ),
        migrations.AlterField(
            model_name='lich',
            name='kotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Kotel', verbose_name='Котельня'),
        ),
        migrations.AlterField(
            model_name='lich',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Place', verbose_name="Тип об'єкта"),
        ),
        migrations.AlterField(
            model_name='lich',
            name='typel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Typel', verbose_name='Тип ліч'),
        ),
        migrations.AlterField(
            model_name='pokaz',
            name='kod_lich',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Lich', verbose_name='Код ліч'),
        ),
    ]
