# Generated by Django 3.0.4 on 2020-04-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lich', '0006_auto_20200402_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код меню')),
                ('menu_name', models.CharField(max_length=30, verbose_name='Назва')),
                ('to_url', models.CharField(max_length=50, verbose_name='Шлях')),
                ('parent_id', models.IntegerField(verbose_name='Головне меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункти меню',
            },
        ),
        migrations.AlterModelOptions(
            name='boiler',
            options={'verbose_name': 'ЦТП', 'verbose_name_plural': 'ЦТП'},
        ),
        migrations.AlterModelOptions(
            name='diln',
            options={'verbose_name': 'Дільниця', 'verbose_name_plural': 'Дільниці'},
        ),
        migrations.AlterModelOptions(
            name='kms',
            options={'verbose_name': 'Місця встановлення', 'verbose_name_plural': 'Місця встановлення'},
        ),
        migrations.AlterModelOptions(
            name='kotel',
            options={'verbose_name': 'Котельня', 'verbose_name_plural': 'Котельні'},
        ),
        migrations.AlterModelOptions(
            name='lich',
            options={'verbose_name': 'Лічильник', 'verbose_name_plural': 'Лічильники'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': "Тип об'єкту", 'verbose_name_plural': "Типи об'єктів"},
        ),
        migrations.AlterModelOptions(
            name='pokaz',
            options={'verbose_name': 'Показ', 'verbose_name_plural': 'Покази'},
        ),
        migrations.AlterModelOptions(
            name='typel',
            options={'verbose_name': 'Тип лічильника', 'verbose_name_plural': 'Типи лічильників'},
        ),
        migrations.AlterField(
            model_name='lich',
            name='boiler',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='lich.Boiler', verbose_name='Бойлерна'),
        ),
        migrations.AlterField(
            model_name='lich',
            name='diln',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Diln', verbose_name='Дільниця'),
        ),
        migrations.AlterField(
            model_name='lich',
            name='kms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Kms', verbose_name='Місце встан'),
        ),
        migrations.AlterField(
            model_name='lich',
            name='kotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Kotel', verbose_name='Котельня'),
        ),
        migrations.AlterField(
            model_name='lich',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Place', verbose_name="Тип об'єкта"),
        ),
        migrations.AlterField(
            model_name='lich',
            name='typel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Typel', verbose_name='Тип ліч'),
        ),
        migrations.AlterField(
            model_name='pokaz',
            name='kod_lich',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lich.Lich', verbose_name='Код ліч'),
        ),
    ]
